const SET_CURRENT_CITY = 'SET_CURRENT_CITY';

const SET_WEATHER_DATA = 'SET_WEATHER_DATA';

const SET_FORECAST_DATA = 'SET_FORECAST_DATA';

const ADD_CITY = 'ADD_CITY';

const REMOVE_CITY = 'REMOVE_CITY';

export {SET_CURRENT_CITY, SET_WEATHER_DATA, SET_FORECAST_DATA, ADD_CITY, REMOVE_CITY};